baseURL = 'https://www.jemdavies.co.uk/'
languageCode = 'en-us'
title = ''

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
title = "Jem Davies"
author = "Jem Davies"
description = "Data Engineer"
profilePicture = "profile.jpeg"
contentratio = 0.9
displayMode = "dark"
favicon = "favicons/"
doNotLoadAnimations = true
mainSections = []

[[params.socialIcons]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/jem-davies/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jeremiah-raftery-davies/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:jeremiahrdavies@gmail.com"

[menu]

  [[menu.main]]
  name = "About"
  identifier = "About"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Contact"
  weight = 300
  identifier = "contact"
  url = "/contact/"
